name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker-compose
    
    - name: Build Docker images
      run: |
        docker-compose build
    
    - name: Run tests
      run: |
        docker-compose run --rm client npm run test
        docker-compose run --rm server pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker-compose build
        docker push $ECR_REGISTRY/client:latest
        docker push $ECR_REGISTRY/server:latest

    - name: Deploy to ECS
      run: |
        aws ecs update-service --cluster my-ecs-cluster --service my-client-service --force-new-deployment
        aws ecs update-service --cluster my-ecs-cluster --service my-server-service --force-new-deployment